### ISSUE TITLE
Docs: please explain exactly how krd connects to my phone

### ISSUE THREAD

**Issue by noamtamim** [kryptco/www#14]
I mean on the network level. They are not connected via Bluetooth, they don't have to be on the same Wifi network -- this must mean a krypt.co web service is acting as a proxy. However, [the security doc](https://krypt.co/docs/security/security-architecture.html) says "Krypton is designed such that you do not have to trust us, krypt.co, to **operate any third party service**".

So even if I don't need to trust you with my key (because you don't have it), I still need to trust your servers to be always online.

**Comment by agrinman** [comment]
We describe this in that document here: https://krypt.co/docs/security/security-architecture.html#the-pairing-protocol. We use three types of communication channels: AWS SQS (your computer and phone directly talk to SQS to read/write messages encrypted,authenticated requests on queues, AWS SNS (Google's and Apple's push notification services to deliver signing requests), and Bluetooth (for a non-network based "offline" mode).

You don't have trust us to run an honest service because all communication is encrypted and signed with keys that only your devices have. Yes you need to rely on our service to be up and running if you have bluetooth *is not enabled*.
